from TTS.api import TTS
import random
from flask import Flask, request, jsonify , send_file
from flask_cors import CORS
import asyncio

app = Flask(__name__)
CORS(app)

tts = TTS("tts_models/multilingual/multi-dataset/xtts_v2", gpu=False)

def generate_random_code():
    code = ''.join(random.choices('0123456789', k=5))
    return code

audio_path = [ '/workspaces/codespaces-jupyter/jarvis-voice/0.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/1.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/2.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/3.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/4.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/5.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/6.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/7.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/8.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/9.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/10.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/11.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/12.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/13.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/14.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/15.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/16.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/17.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/18.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/19.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/20.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/21.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/22.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/23.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/24.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/25.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/26.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/27.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/28.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/29.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/30.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/31.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/32.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/33.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/34.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/35.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/36.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/37.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/38.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/39.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/40.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/41.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/42.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/43.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/44.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/45.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/46.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/47.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/48.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/49.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/50.wav'
]

audio_path2 = ['/workspaces/codespaces-jupyter/jarvis-voice/51.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/52.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/53.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/54.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/55.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/56.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/57.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/58.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/59.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/60.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/61.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/62.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/63.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/64.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/65.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/66.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/67.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/68.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/69.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/70.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/71.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/72.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/73.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/74.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/75.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/76.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/77.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/78.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/79.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/80.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/81.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/82.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/83.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/84.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/85.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/86.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/87.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/88.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/89.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/90.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/91.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/92.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/93.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/94.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/95.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/96.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/97.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/98.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/99.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/100.wav'
]

audio_path3 = ['/workspaces/codespaces-jupyter/jarvis-voice/101.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/102.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/103.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/104.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/105.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/106.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/107.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/108.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/109.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/110.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/111.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/112.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/113.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/114.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/115.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/116.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/117.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/118.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/119.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/120.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/121.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/122.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/123.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/124.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/125.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/126.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/127.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/128.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/129.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/130.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/131.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/132.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/133.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/134.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/135.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/136.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/137.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/138.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/139.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/140.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/141.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/142.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/143.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/144.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/145.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/146.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/147.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/148.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/149.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/150.wav'
]

audio_path4 = ['/workspaces/codespaces-jupyter/jarvis-voice/151.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/152.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/153.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/154.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/155.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/156.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/157.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/158.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/159.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/160.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/161.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/162.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/163.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/164.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/165.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/166.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/167.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/168.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/169.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/170.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/171.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/172.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/173.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/174.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/175.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/176.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/177.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/178.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/179.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/180.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/181.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/182.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/183.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/184.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/185.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/186.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/187.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/188.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/189.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/190.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/191.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/192.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/193.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/194.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/195.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/196.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/197.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/198.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/199.wav',
'/workspaces/codespaces-jupyter/jarvis-voice/200.wav'
]

audio_path5 = ['/workspaces/codespaces-jupyter/jarvis-voice/201.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/202.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/203.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/204.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/205.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/206.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/207.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/208.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/209.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/210.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/211.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/212.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/213.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/214.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/215.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/216.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/217.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/218.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/219.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/220.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/221.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/222.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/223.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/224.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/225.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/226.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/227.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/228.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/229.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/230.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/231.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/232.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/233.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/234.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/235.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/236.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/237.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/238.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/239.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/240.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/241.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/242.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/243.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/244.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/245.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/246.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/247.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/248.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/249.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/250.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/251.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/252.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/253.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/254.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/255.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/256.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/257.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/258.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/259.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/260.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/261.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/262.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/263.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/264.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/265.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/266.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/267.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/268.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/269.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/270.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/271.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/272.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/273.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/274.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/275.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/276.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/277.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/278.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/279.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/280.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/281.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/282.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/283.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/284.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/285.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/286.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/287.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/288.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/289.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/290.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/291.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/292.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/293.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/294.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/295.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/296.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/297.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/298.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/299.wav' ,
'/workspaces/codespaces-jupyter/jarvis-voice/300.wav' 
]

audio_path6 = ['/workspaces/codespaces-jupyter/jarvis-voice/301.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/302.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/303.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/304.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/305.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/306.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/307.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/308.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/309.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/310.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/311.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/312.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/313.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/314.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/315.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/316.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/317.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/318.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/319.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/320.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/321.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/322.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/323.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/324.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/325.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/326.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/327.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/328.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/329.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/330.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/331.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/332.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/333.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/334.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/335.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/336.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/337.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/338.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/339.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/340.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/341.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/342.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/343.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/344.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/345.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/346.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/347.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/348.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/349.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/350.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/351.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/352.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/353.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/354.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/355.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/356.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/357.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/358.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/359.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/360.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/361.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/362.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/363.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/364.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/365.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/366.wav' , 
'/workspaces/codespaces-jupyter/jarvis-voice/367.wav' 
]

def say(text):
    print('Voice syntheziser active!')
    code = generate_random_code()
    tts.tts_to_file(text=text,
                    file_path= "/workspaces/codespaces-jupyter/clips/" + str(code) +".mp3",
                    speaker_wav= audio_path + audio_path2 + audio_path3 + audio_path4 + audio_path5 + audio_path6,
                    language='en')
    return code
    
@app.route('/generate_speech', methods=['POST'])
def speech():
        data = request.get_json()
        print(data)
        if data:
            code = say(data['text'])
            print('done')
            return send_file('./clips/'+str(code)+'.mp3', mimetype='audio/mpeg')
        else:
            print('null')
            return jsonify({'nigger': 'potatop'}), 200


if __name__ == '__main__':
    app.run(debug=True , port=6969)